### ISSUE TITLE
GME doesn't work on listing page

### ISSUE THREAD

**Issue by jenda69** [JRInge/userscripts#14]
For more than month, GME didn't load on listing pages for me.
And today I found out why.

If gmeResources.env.page == "listing" (line 2640) it checks gmeResources.env.loggedin. If it isn't true, it stops script because there are no coordinates.
loggedin (line 128) is true when one of the divs like "ctl00_divSignedIn" exists...
But for whatever reason (on listing page at least) element with login info is not ctl00_divSignedIn but it is ctl00_uxLoginStatus_divSignedIn.
I changed that in my script and GME works now even on listing page.
Could that be updated in script? Or am I only one having this problem?

**Comment by JRInge** [comment]
I've been working on this and some other related bugs in the GME development branch.  The fix will be rolled out soon!

**Comment by JRInge** [comment]
Closed by #15.
