### ISSUE TITLE
loadListing: TypeError: $(...)[0].parentNode.parentNode.children[7] is undefined

### ISSUE THREAD

**Issue by mkyral** [JRInge/userscripts#31]
If cache has parking waypoint, map in listing is not loaded correctly. Cache and waypoints are not shown.
E.g.: https://www.geocaching.com/geocache/GC2MCYQ_kaple-sv-kunhuty

It is caused by code:

```js
$("#awpt_"+parking.pf)[0].parentNode.parentNode.children[7].innerHTML +=
```

There are only 6 columns in the table now.
![obrazek](https://user-images.githubusercontent.com/155542/34181308-0c6f9b12-e512-11e7-86e0-8ebbae19c318.png)

Max index is 5. So fix is simple - just replace children[7] with children[5].

**Comment by JRInge** [comment]
Closing - this was fixed in v0.8.1 (commit fc18032).
