### ISSUE TITLE
the new "Map List" function does not work with GME

### ISSUE THREAD

**Issue by PontiacCZ** [JRInge/userscripts#35]
GC has just introduced a new list function "Map List" which displays listed caches on the geocaching map.

![image](https://user-images.githubusercontent.com/9153595/37198600-1fcc104a-237f-11e8-9d6f-b570714bf7aa.png)

For whatever reason with GME on the map loads all caches in the area:

![image](https://user-images.githubusercontent.com/9153595/37198727-9285ba82-237f-11e8-917a-c0647ad25a05.png)

With GME off the map looks as expected:

![image](https://user-images.githubusercontent.com/9153595/37198766-a9466546-237f-11e8-8f05-b99521a7daf9.png)

**Comment by JRInge** [comment]
I've made some changes in the GME development branch that ought to fix this (see commit 96b577e). However, as I'm not a Premium Member, I can't test it fully.

@PontiacCZ - can you try this version of the script? https://github.com/JRInge/userscripts/raw/GME-Development/GeocachingMapEnhancements/Geocaching_Map_Enhancements.user.js 
If it fixes the problem (and doesn't break anything else), I'll roll out an update onto OpenUserJS.org

**Comment by PontiacCZ** [comment]
Hi, it does work! :) Just as expected, I verified with a few more lists. I also tried:
-  browsing the map with all caches displayed as usual
- switching of/off the map filters
- switching between layers
- opening caches from the map

 and everything looks good so far. I guess it is safe to publish this update. 

And thank you for your quick reaction! :-)
