### ISSUE TITLE
GeocachingHeight: Suggest using Open Elevation API

### ISSUE THREAD

**Issue by Krevo** [JRInge/userscripts#38]
The geocaching Height script is no longer working here.
I've got this eror message in the google map response : 
```
"{
"error_message": "You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account",
"results": [],
"status": "REQUEST_DENIED"
}
```
I suggest to use the "Open elevation API".
So, the call in the script would be :
`url: "https://api.open-elevation.com/api/v1/lookup?locations=" + coords,`

Tested OK here, just needed to also update the "@connect" in the user script header.

Thanks in advance for reading and considering this issue.

**Comment by Krevo** [comment]
Note: Open Elevation API seems a bit slow (but is better than nothing)

**Comment by JRInge** [comment]
Thanks for pointing out the problem.  I had a look at the Open Elevation API, but I think I will try using the [GeoNames Aster GDEM](http://www.geonames.org/export/web-services.html#astergdem) service first.  That offers data at 90m horizontal resolution; Open Elevation only seems to give 250m resolution.

If the script starts maxing out the free limit for GeoNames, I'll switch to Open Elevation.  That doesn't seem to have a usage limit.

**Comment by Krevo** [comment]
Thanks for your reply.
"GeoName Aster" seems very fast ;-)

**Comment by JRInge** [comment]
Looks like this is working in v1.1.3.

**Comment by Krevo** [comment]
Works perfectly.
Thanks.
