### ISSUE TITLE
Geocaching Height : no more working  (June 2019) since link has changed

### ISSUE THREAD

**Issue by Krevo** [JRInge/userscripts#42]
I've got the error :
`TypeError: Cannot read property 'length' of null
    at getCoords (userscript.html?id=e50fbb23-e0b0-4d26-a4f1-aedc68293fb5:60)`

(seems to be on line 54 : `       return (target && target.href && (matched = target.href.match(pattern), matched.length === 3) `)

Currently _lat_ and _lng_ are grabbed from the link with id _ctl00_ContentBody_uxViewLargerMap_
but this kind of link seems to have changed, since a recent update on maps.

I actually have this link :
`<a_ id="ctl00_ContentBody_uxViewLargerMap" title="Voir une plus grande carte" href="/play/map/GC1Y014" target="_blank" rel="noopener noreferrer">Afficher la carte agrandie</a>`

Locally I've replaced the line :
`const coords = getCoords("ctl00_ContentBody_uxViewLargerMap");`
with :
`const coords = {lat: lat, lng: lng};`

as the page seems to expose directly vars called _lat_ and _lng_ as I can se on the source of the page :

`<script type="text/javascript">
   var isLoggedIn = true;
   var lat=45.879233, lng=6.887133, guid='0157909c-6d0d-4ef7-9f07-4dd858dc1f89';
</script>`

**Comment by JRInge** [comment]
I think this is fixed in the [Height Development](https://github.com/JRInge/userscripts/tree/Height-Development/GeocacheHeight) branch.  If it works for you too @Krevo, I'll deploy the fix tomorrow.

**Comment by Krevo** [comment]
I confirm, it works for me ! :-)
Thanks.
